-- CreateEnum
CREATE TYPE "ChapterKind" AS ENUM ('TITLE_PAGE', 'COPYRIGHT', 'EPIGRAPH', 'DEDICATION', 'TOC', 'PROLOGUE', 'INTRODUCTION', 'PART', 'CHAPTER', 'ACKNOWLEDGMENTS', 'ABOUT_AUTHOR', 'ALSO_BY');

-- AlterTable
ALTER TABLE "chapter" ADD COLUMN "kind" "ChapterKind" NOT NULL DEFAULT 'CHAPTER';
ALTER TABLE "chapter" ADD COLUMN "data" JSONB;
