import nextPlugin from '@next/eslint-plugin-next';
import react from './react.js';

/**
 * Flat ESLint config for the Next.js app (extends the React-library preset
 * and adds Next.js-specific rules).
 * @type {import('eslint').Linter.Config[]}
 */
export default [
  // next-env.d.ts is generated by Next and uses triple-slash references.
  { ignores: ['next-env.d.ts', '.next/**'] },
  ...react,
  {
    files: ['**/*.{ts,tsx,jsx}'],
    plugins: {
      '@next/next': nextPlugin,
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
    },
  },
];
